###
POST http://localhost:8080/api/v1/carparts/create
Content-Type: application/json

{
  "id": 0,
  "name": "brakes",
  "productionDate": 1713787922,
  "expiryDate": 1713787922,
  "barCode": 12345,
  "cost": 1234
}
###
POST http://localhost:8080/api/v1/carparts/create/extended
Content-Type: application/json

{
  "id": 0,
  "name": "brakes",
  "productionDate": 1713787922,
  "expiryDate": 1713787922,
  "barCode": 12345,
  "cost": 1234
}

###
POST http://localhost:8080/api/v1/carparts/name
Content-Type: application/json

{
   "name": "ignition"
}

###
POST http://localhost:8080/api/v1/carparts/name
Content-Type: application/json

{
   "name": "ignition for the ignition for the ignition"
}

###
POST http://localhost:8080/api/v1/carparts/impossible
Content-Type: application/json

{
   "name": "ignition"
}

###
POST http://localhost:8080/api/v1/carparts/impossible
Content-Type: application/json

{
   "name": "ignition for the ignition for the ignition"
}
